### ISSUE TITLE
Assignment - 5: Palindrome Checker

### ISSUE THREAD

**Issue by 43bit23** [vtcbca/basic-programming-61bit23#10]
What is a palindrome?

**Comment by 61bit23** [comment]
A palindrome is a word, phrase, number, or other sequence of characters that reads the same forward and backward

**Comment by 43bit23** [comment]
Can a palindrome have spaces or punctuation?

**Comment by 61bit23** [comment]
A palindrome is a word, phrase, number, or other sequence of characters that reads the same forward and backward (ignoring spaces, punctuation, and capitalization).

**Comment by 61bit23** [comment]
Yes, spaces and punctuation can be ignored when checking for palindromes.

**Comment by 43bit23** [comment]
How do you check if a string is a palindrome in Python?

**Comment by 61bit23** [comment]
Reverse the string and compare it to the original. If they are the same, the string is a palindrome

**Comment by 43bit23** [comment]
What is a simple algorithm to check for a palindrome?

**Comment by 61bit23** [comment]
Compare the first character with the last, the second with the second-last, and so on. If all characters match, it's a palindrome.

**Comment by 43bit23** [comment]
How do you ignore spaces and punctuation in a palindrome checker?

**Comment by 61bit23** [comment]
Remove all non-alphanumeric characters and convert the string to lowercase before checking.

**Comment by 43bit23** [comment]
Okay
