### ISSUE TITLE
Assignment 6-  Pattern of *

### ISSUE THREAD

**Issue by 52bit23** [vtcbca/basic-programming-61bit23#11]
pattern means?

**Comment by 61bit23** [comment]
A pattern is a sequence or arrangement that follows a specific rule or logic.

**Comment by 52bit23** [comment]
What kind of pattern is used in the given star pattern?

**Comment by 61bit23** [comment]
The given pattern is a simple increasing pattern of stars, where the number of stars increases by 1 in each row.

**Comment by 52bit23** [comment]
How do you print a simple star pattern in Python?

**Comment by 61bit23** [comment]
Use nested loops to print stars. The outer loop handles rows, and the inner loop handles printing the stars.

**Comment by 52bit23** [comment]
How do you control the number of stars printed in each row?

**Comment by 61bit23** [comment]
Use the row number (starting from 1) to print that many stars in each iteration.

**Comment by 52bit23** [comment]
How do you print the star pattern up to n rows?

**Comment by 61bit23** [comment]
Use a loop to iterate through rows, and for each row, print the stars equal to the row number.
