### ISSUE TITLE
Assignment-8 : Pattern of Alphabets

### ISSUE THREAD

**Issue by 58bit23** [vtcbca/basic-programming-61bit23#12]
What is the pattern of alphabets in this example?

**Comment by 61bit23** [comment]
The pattern follows a central letter and symmetrically arranges other letters outward from the center. For example, the second row has "A B A" and the third has "A B C B A."

**Comment by 58bit23** [comment]
How does the number of spaces change in each row?

**Comment by 61bit23** [comment]
The number of spaces decreases as you move down the rows. The first row has the most spaces, and each subsequent row has fewer

**Comment by 58bit23** [comment]
How do you print an alphabet pattern with "n" rows in Python?

**Comment by 61bit23** [comment]
Use loops to handle both spaces and alphabets. The outer loop controls the rows, and the inner loop prints the appropriate characters with spaces in between.

**Comment by 58bit23** [comment]
How do you determine the alphabet to print in each row?

**Comment by 61bit23** [comment]
The alphabet for each row increases in the middle and then decreases symmetrically. You can use the ASCII value of characters to print the appropriate letters.

**Comment by 58bit23** [comment]
Ok thanks
