### ISSUE TITLE
Assignment 1-factorial

### ISSUE THREAD

**Issue by 61bit23** [vtcbca/basic-programming-61bit23#2]
what is the meaning of factorial ?

**Comment by 62bit23** [comment]
it's very simple. A factorial, denoted by an exclamation mark (!), is a mathematical operation that multiplies a number by all of the positive integers below it.

**Comment by 63bit23** [comment]
can say it simple way ?

**Comment by 62bit23** [comment]
Factorials are used in various areas of mathematics, particularly in combinatorics (to count permutations and combinations), algebra, and calculus.

**Comment by 63bit23** [comment]
please give me some example for it ?

**Comment by 64bit23** [comment]
5!=5×4×3×2×1=120

**Comment by 64bit23** [comment]
can you understand what i'm say ?

**Comment by 64bit23** [comment]
yes it's very simply to understand.

**Comment by 65bit23** [comment]
what is key point of factorial ?

**Comment by 65bit23** [comment]
Factorial is the product of all positive integers up to a given number.

**Comment by 65bit23** [comment]
Factorial is the product of all positive integers up to a given number.

**Comment by 63bit23** [comment]
Factorial is the product of all positive integers up to a given number.

**Comment by 62bit23** [comment]
ok...but what is the formula of it ?

**Comment by 63bit23** [comment]
n! = n × (n-1) × (n-2) × (n-3)

**Comment by 61bit23** [comment]
thank you everyone.
