### ISSUE TITLE
Assignment 2-prime number

### ISSUE THREAD

**Issue by 62bit23** [vtcbca/basic-programming-61bit23#3]
what is prime number?

**Comment by 65bit23** [comment]
A **prime number** is a natural number greater than 1 that has no positive divisors other than 1 and itself.

**Comment by 62bit23** [comment]
how can we find the prime number ?

**Comment by 61bit23** [comment]
it means the number which cannot be divided by any other number except by itself.

**Comment by 64bit23** [comment]
it is very difficult to understand.

**Comment by 65bit23** [comment]
you are right.

**Comment by 61bit23** [comment]
but you try to understand it continuously . you can learn it.

**Comment by 63bit23** [comment]
give me some example ?

**Comment by 65bit23** [comment]
3,5,7

**Comment by 62bit23** [comment]
i'm understand it but it's useful for us ?

**Comment by 64bit23** [comment]
Cyber-age security
Encryption and decryption

**Comment by 62bit23** [comment]
thank you for your great response .
