### ISSUE TITLE
assignment 4 Reverse String

### ISSUE THREAD

**Issue by 57bit23** [vtcbca/basic-programming-61bit23#4]
Regarding String

**Comment by 57bit23** [comment]
what is string?

**Comment by 44bit23** [comment]
A string is just a piece of text. It can be a word, sentence, or even just a letter or number.

**Comment by 56bit23** [comment]
What kind of data is stored in String?

**Comment by 57bit23** [comment]
What kind of data is stored in string?

**Comment by 44bit23** [comment]
A string stores text data, including letters, numbers, symbols, spaces, and punctuation.

**Comment by 57bit23** [comment]
Ok

**Comment by 57bit23** [comment]
Can you give me the example of string?

**Comment by 44bit23** [comment]
**Hello 57bit23 !** :This is an example of string

**Comment by 57bit23** [comment]
Ok How can you initialize a string in python

**Comment by 57bit23** [comment]
Thank you @44bit23 for your response
