### ISSUE TITLE
Assignment 1 factorial number

### ISSUE THREAD

**Issue by 61bit23** [vtcbca/basic-programming-61bit23#6]
How can i solve this problem?

**Comment by 55bit23** [comment]
Use one of these methods:

1. Iterative approach: Loop from 1 to 𝑛n

2. Recursive approach: Call the function recursively with 

           𝑛−1n−1.

3. Built-in library: Use Python’s math.factorial.

**Comment by 61bit23** [comment]
can you explain first in detail?

**Comment by 55bit23** [comment]
code:

```
def factorial_iterative(n):
    if n < 0:
        return "Factorial is not defined for negative numbers."
    result = 1
    for i in range(1, n + 1):  # Loop from 1 to n
        result *= i
```
    return result

# Example usage
number = int(input("Enter a non-negative integer: "))
print(f"The factorial of {number} is {factorial_iterative(number)}.")
```



How It Works:
1. If \( n \) is negative, display an error message.
2. Initialize `result` as 1.
3. Use a loop to multiply `result` by each number from 1 to \( n \).
4. Return the final `result`.

**Comment by 61bit23** [comment]
What is the largest factorial value you can calculate in Python?

**Comment by 55bit23** [comment]
No strict limit in Python: Unlike some programming languages with fixed integer sizes (e.g., 32-bit or 64-bit), Python’s integers are only limited by available memory.

**Comment by 61bit23** [comment]
How does factorial relate to permutations?

**Comment by 55bit23** [comment]
Factorials are directly related to permutations because permutations involve arranging objects in different orders, and the factorial provides the total number of such arrangements
