### ISSUE TITLE
Assignment-2:  Prime Number Checker

### ISSUE THREAD

**Issue by 65bit23** [vtcbca/basic-programming-61bit23#7]
What is a prime number?

**Comment by 61bit23** [comment]
A prime number is a number greater than 1 that has only two factors: 1 and itself.

**Comment by 61bit23** [comment]
What are the first five prime numbers?

**Comment by 61bit23** [comment]
What are the first five prime numbers?

**Comment by 65bit23** [comment]
What are the first five prime numbers?

**Comment by 61bit23** [comment]
The first five prime numbers are 2, 3, 5, 7, and 11.

**Comment by 65bit23** [comment]
How do you check if a number is prime in a program?

**Comment by 61bit23** [comment]
Divide the number by all integers from 2 to the square root of the number and check for no remainder

**Comment by 65bit23** [comment]
What is the base case for checking prime numbers?

**Comment by 61bit23** [comment]
If the number is less than 2, it is not a prime number.

**Comment by 65bit23** [comment]
How do you optimize a prime number checker for large inputs?

**Comment by 61bit23** [comment]
Check divisors only up to the square root of the number and skip even numbers (after 2).

**Comment by 65bit23** [comment]
Okay
