### ISSUE TITLE
Assignment-3 : Fibonacci Sequence Generator

### ISSUE THREAD

**Issue by 53bit23** [vtcbca/basic-programming-61bit23#8]
What is a Fibonacci sequence?

**Comment by 61bit23** [comment]
A Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones, starting with 0 and 1.

**Comment by 53bit23** [comment]
What are the first five Fibonacci numbers?

**Comment by 61bit23** [comment]
The first five Fibonacci numbers are 0, 1, 1, 2, 3.

**Comment by 53bit23** [comment]
Is the Fibonacci sequence infinite?

**Comment by 61bit23** [comment]
Yes, the Fibonacci sequence goes on forever.

**Comment by 53bit23** [comment]
How do you generate the Fibonacci sequence up to n terms?

**Comment by 61bit23** [comment]
Use a loop to calculate and print the first n Fibonacci numbers.

**Comment by 53bit23** [comment]
How do you store the Fibonacci sequence in a program?

**Comment by 61bit23** [comment]
Use a list or array to store the sequence as you calculate it.

**Comment by 53bit23** [comment]
Okk

**Comment by 61bit23** [comment]
A string is a sequence of characters, such as words, sentences, or symbols.
