### ISSUE TITLE
Assignment-4 : Reverse String

### ISSUE THREAD

**Issue by 41bit23** [vtcbca/basic-programming-61bit23#9]
What is a string in programming?

**Comment by 41bit23** [comment]
What does it mean to reverse a string?

**Comment by 61bit23** [comment]
A string is a sequence of characters, such as words, sentences, or symbols.

**Comment by 41bit23** [comment]
What does it mean to reverse a string?

**Comment by 61bit23** [comment]
Reversing a string means arranging its characters in the opposite order.
Example: "hello" becomes "olleh".

**Comment by 41bit23** [comment]
What happens when you reverse an empty string?

**Comment by 61bit23** [comment]
The result is still an empty string.

**Comment by 61bit23** [comment]
Use slicing: string[::-1].

**Comment by 41bit23** [comment]
How do you reverse a string in Python?

**Comment by 61bit23** [comment]
Use slicing: string[::-1].

**Comment by 41bit23** [comment]
What function can you use to reverse a string in many programming languages?

**Comment by 61bit23** [comment]
functions like reverse() or use built-in methods for reversal.

**Comment by 41bit23** [comment]
Ok thanks
